version: '3.8'

services:
  web:
    build:
      context: ./djbnb_backend/server
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djbnb_backend/server:/usr/src/server/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cerelise
      - POSTGRES_PASSWORD=wang0926
      - POSTGRES_DB=djangobnb

volumes:
  postgres_data:
      